services:
  # A Docker web service
  - type: web
    name: salary prediction
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: cd starter && uvicorn main:app --host 0.0.0.0 --port $PORT